Bugfix/regmap
wirenboard/wb-embedded-controller pull request #35
Opened 2024-07-12 09:26 UTC by pgasheev

Фундаментальная проблема в regmap: между regmap_is_region_changed и regmap_get_region_data может произойти обмен по spi, regmap станет занятым и regmap_get_region_data не сработает. То же самое с regmap_clear_changed. В итоге 3 функции слил в одну

2024-07-15 14:20 UTC, nikitoz236 approved these changes

2024-07-15 14:20 UTC, nikitoz236 commented on include/regmap-int.h
> +bool regmap_is_region_changed(enum regmap_region r, void * data, size_t size);
ну с названием конечно нужно поразбираться. get_changed_data например

2024-07-15 14:20 UTC, nikitoz236 commented on src/regmap.c
> +static uint16_t w_address = 0;                                      // Адрес текущей операции записи
неочень понятно какую проблему решал разделением адресов. комментарий бы хотябы

2024-07-15 14:21 UTC, nikitoz236 reviewed
переименовать функию точно надо

2024-07-15 14:22 UTC, nikitoz236 requested changes
переименовать функию точно надо

2024-07-15 19:19 UTC, pgasheev commented on include/regmap-int.h
> +bool regmap_is_region_changed(enum regmap_region r, void * data, size_t size);
Переименовал

2024-07-15 19:19 UTC, pgasheev commented on src/regmap.c
> +static uint16_t w_address = 0;                                      // Адрес текущей операции записи
Коммент и запись в ченжлог добавил

2024-07-16 10:00 UTC, nikitoz236 approved these changes

2024-07-16 10:09 UTC, merged