Feature/wb85 wbmz6
wirenboard/wb-embedded-controller pull request #41
Opened 2024-08-08 12:23 UTC by pgasheev

Поддержка WBMZ6

2024-09-10 11:00 UTC, ad7718 requested changes

2024-09-11 07:24 UTC, pgasheev commented on src/wbmz6-battery.c
> +#define AXP221S_POWER_STATUS                        0x00
Поправил

2024-09-11 07:25 UTC, pgasheev commented on src/wbmz6-battery.c
> +#define AXP221S_REG_BATTERY_DISCHARGE_CURRENT       0x7C
Предлагаю оставить. Они там не используются в основном потому, что два подряд регистра читаются. Так хотя бы видно, что они подряд идут

2024-09-11 07:25 UTC, pgasheev commented on src/wbmz6-battery.c
> +#define AXP221S_OP_MODE                             0x01
Ответил в комменте ниже, предлагаю оставить

2024-09-11 07:28 UTC, pgasheev commented on src/wbmz6-battery.c
> +#define AXP221S_TEMPERATURE_LIMIT_MV_TO_VAL(mv)     ((mv) / 16.0 / 0.8)
А почему тут 48.5 должно получиться? Это значение регистра в своих попугаях, а не температура в градусах

2024-09-11 07:29 UTC, pgasheev commented on src/wbmz6-battery.c
> +static inline uint16_t axp221s_read_u16(uint8_t reg)
Убрал

2024-09-11 07:31 UTC, pgasheev commented on src/wbmz6-battery.c
> +void wbmz6_battery_update_params(struct wbmz6_params *params)
Сделал, в суперкапе тоже поправил

2024-09-11 07:32 UTC, pgasheev commented on src/wbmz6-battery.c
> +    status->charging_current_ma = axp221s_get_adc_value_from_buf(&buf[2], 8, 5) >> 1;
// lsb is 0.5mA
сдвиг вместо деления на 2, написал подробнее

2024-09-11 07:36 UTC, pgasheev commented on src/wbmz6-battery.c
> +    status->is_charging = (buf[0] & 0x04) ? true : false;
Да, переделал, только вместо 3 строчек получилось 15

2024-09-11 08:04 UTC, pgasheev commented on src/wbmz6-battery.c
> +    status->capacity_percent &= 0x7F;   // clear bit 7 - calculation status flag
Добавил дефайнов

2024-09-11 08:08 UTC, pgasheev commented on include/wbmz6-battery.h
> +
Добавил в wbmz6-battery.c

2024-09-11 08:08 UTC, pgasheev commented on include/wbmz6-supercap.h
> +
Есть в .с файле

2024-09-11 08:08 UTC, pgasheev commented on src/wbmz6-supercap.c
> +void wbmz6_supercap_update_params(struct wbmz6_params *params)
Сделал

2024-09-11 08:10 UTC, pgasheev commented on src/wbmz-subsystem.c
> +    case WBMZ6_DEVICE_BATTERY:
Сделал

2024-09-11 08:30 UTC, ad7718 commented on src/wbmz6-battery.c
> +#define AXP221S_TEMPERATURE_LIMIT_MV_TO_VAL(mv)     ((mv) / 16.0 / 0.8)
В коде есть такая строчка #define WBEC_WBMZ6_BATTERY_VHTF_DISCHARGE_VADC_MV       499     // 48.5 °C
Из неё я сделал вывод что из значения 499 должно получиться 48.5 градусов, глубже не копал.

2024-09-11 08:32 UTC, ad7718 commented on src/wbmz6-battery.c
> +    status->is_charging = (buf[0] & 0x04) ? true : false;
я тоже иногда хочу использовать, не вроде как кодовый стиль не позволяет, или его надо пересмотреть

2024-09-11 08:52 UTC, ad7718 requested changes

2024-09-11 08:52 UTC, ad7718 commented on src/wbmz6-battery.c
>      buf[0] &= (1 << bits_in_first_reg) - 1;
Вообще вроде у нас где-то были макросы для конструкций вида "(1 << bits_in_first_reg) - 1", когда читаешь такой какой без абстракции, не сразу понимаешь как оно работает, хочется меньше думать когда читаешь код

2024-09-11 08:52 UTC, ad7718 commented on src/wbmz6-battery.c
> +    status->charging_current_ma = axp221s_get_adc_value_from_buf(&buf[2], 8, 5) >> 1;
если тут деление на 2, то я бы лучше написал просто / 2, почти уверен что компилятор сам выберет оптимальный способ, читаемость кода повысится https://stackoverflow.com/a/6357114

2024-09-11 08:52 UTC, ad7718 commented on src/wbmz6-battery.c
> +    status->capacity_percent &= AXP221S_REG_BATTERY_LEVEL_LEVEL_MASK;
тут два раза LEVEL получилось, непонятное название

2024-09-11 09:02 UTC, pgasheev commented on src/wbmz6-battery.c
> +#define AXP221S_TEMPERATURE_LIMIT_MV_TO_VAL(mv)     ((mv) / 16.0 / 0.8)
Не должно, тут мы задаем милливольты на пине TS, которые должны сами посчитать по таблице. Далее эти мииливольты пересчитываются в значение регистра. Добавил в коммент

2024-09-11 09:07 UTC, pgasheev commented on src/wbmz6-battery.c
>      buf[0] &= (1 << bits_in_first_reg) - 1;
Ключевое слово "где-то" )
Тут наши либы не используются. Добавил макрос

2024-09-11 09:08 UTC, pgasheev commented on src/wbmz6-battery.c
> +    status->capacity_percent &= AXP221S_REG_BATTERY_LEVEL_LEVEL_MASK;
Ну тут типа название регистра battery_level и название поля level. Убрал дублирование

2024-09-11 09:09 UTC, pgasheev commented on src/wbmz6-battery.c
> +#define AXP221S_TEMPERATURE_LIMIT_MV_TO_VAL(mv)     ((mv) / 16.0 / 0.8)
Коммент есть в config_wb85.h

2024-09-11 19:54 UTC, ad7718 approved these changes

2024-09-12 06:27 UTC, merged