Feature/wb85 uarts
wirenboard/wb-embedded-controller pull request #46
Opened 2024-08-30 09:53 UTC by pgasheev

2024-09-10 09:30 UTC, nikitoz236 commented on src/usart_tx.c
> +    check_debug_uart_initialized();
usart_wait_tranmission_complete тоже может тут ждать чтобы не блокировать ? там же фифо всеравно есть

2024-09-10 09:30 UTC, nikitoz236 commented on src/uart-regmap.c
> +        rx_irq_needed = true;
просто вместо каждого = true может return true делать?

2024-09-10 09:30 UTC, nikitoz236 commented on src/spi-slave.c
> +#define SPI_SLAVE_PAD_WORDS_COUNT                5
Это расчитано ? может меньше сделать ? Или нужно вычисление обоснование сюда прокоментировать

2024-09-10 09:30 UTC, nikitoz236 commented on src/spi-slave.c
> +        // Это не мешает, если операция - запись, то в ответ всё равно передаем
такие вещи обычно проверяются через двойной иф, флаг сработки и включеность прерывания

2024-09-10 09:30 UTC, nikitoz236 commented on src/irq-subsystem.c
> +    static inline void init_int_gpio(void) {}
дак может сделать irq_do_periodic_work пустой тогда ?

2024-09-10 09:30 UTC, nikitoz236 commented on src/irq-subsystem.c
> +    static inline void set_int_gpio_active(void)
как будто надо одну функцию с аргументом, всеравно ты в месте где используешь располагаешь их в if - else

2024-10-11 09:19 UTC, pgasheev commented on src/usart_tx.c
> +    check_debug_uart_initialized();
В любом случае надо сначала проверить, инициализирован ли уарт, а потом уже к его регистрам обращаться. Влили это отдельным PR

2024-10-11 09:20 UTC, pgasheev commented on src/uart-regmap.c
> +        rx_irq_needed = true;
Да, переделал

2024-10-11 09:21 UTC, pgasheev commented on src/irq-subsystem.c
> +    static inline void init_int_gpio(void) {}
Нет, там не только управление GPIO, а ещё битики выставляются в регистрах

2024-10-17 13:30 UTC, nikitoz236 requested changes

2024-10-17 13:30 UTC, nikitoz236 commented on src/uart-regmap.c
> +void uart_regmap_process_start_tx(const struct uart_descr *u, const struct uart_tx *tx)
зачем ? нигде не используется

2024-10-17 13:30 UTC, nikitoz236 commented on src/uart-regmap-subsystem.c
> +        if (regmap_get_data_if_region_changed(uart_descr[i].start_tx_region, &uart_tx_start, sizeof(uart_tx_start))) {
кто сбросит там единичку ?

2024-10-17 13:30 UTC, nikitoz236 commented on src/uart-regmap-subsystem.c
> +            if (!exchange_received[i]) {
я не понимаю что делает этот флаг

2024-10-17 13:30 UTC, nikitoz236 commented on src/uart-regmap-subsystem.c
> +                uart_ctx[i].want_to_tx = 1;
это булевая переменная ? в разнобой гдето 1 гдето true. посмотри все пожалуйста

2024-10-17 13:30 UTC, nikitoz236 commented on src/uart-regmap-subsystem.c
> +static bool exchange_received[MOD_COUNT];
надо хорошо подписать что все 3 переменные значат. и почему они не в ctx

2024-10-17 13:30 UTC, nikitoz236 commented on include/uart-regmap-internal.h
> +    struct {
а куда они потом ?

2024-10-17 13:30 UTC, nikitoz236 commented on src/uart-regmap.c
> +void uart_regmap_process_exchange(const struct uart_descr *u, union uart_exchange *e)
ну так давай и назовем tx_only

2024-10-17 13:30 UTC, nikitoz236 commented on src/uart-regmap.c
> +                // При следующем обмене данные будут в формате с ошибками
а следующее когда ? сразу потомучто флаг не отпускаем ? раздвинуть в буффере байты не проще ?

2024-10-17 13:30 UTC, nikitoz236 commented on src/uart-regmap.c
> +    ATOMIC {
в статик инлайн может завернуть?

2024-10-24 07:16 UTC, pgasheev commented on include/uart-regmap-subsystem.h
> +void uart_subsystem_deinit(void);
Не используется, убрал

2024-10-24 07:18 UTC, pgasheev commented on include/uart-regmap-types.h
> +        struct {
Там то же самое, но тут мы собираем данные для последующей отправки по spi. А в circ_buffer - данные складываются асинхронно при приеме байта. Перекладывать их в регмап можно только в определенный момент, после того как считаны предыдущие данные

2024-10-24 07:19 UTC, pgasheev commented on src/uart-regmap.c
> + * 5) Процесс продолжается до тех пор, пока во внутреннем кольцевом буфере есть ЕС есть данные
Убрал

2024-10-24 07:20 UTC, pgasheev commented on src/uart-regmap.c
> +#define UART_RX_BYTE_ERROR_PE               BIT(0)
Где?

2024-10-24 07:22 UTC, pgasheev commented on src/uart-regmap.c
> +    if ((ctrl->parity == UART_PARITY_NONE) ||
Сделал

2024-10-24 07:22 UTC, pgasheev commented on src/uart-regmap.c
> +    if ((ctrl->baud_x100 >= 12) && (ctrl->baud_x100 <= 1152)) {
Технически да, на стороне ЕС не вижу смысла запрещать

2024-10-24 07:25 UTC, pgasheev commented on src/uart-regmap-subsystem.c
> +                uart_ctx[i].ctrl.ctrl_applyed = 0;
Так вроде нет смысла делать две переменные, которые будут друг друга дублировать. Тут ctrl_applyed сбрасывается в 0 уже после того как в regmap скопировалось, так что с ним уже можно делать всё что угодно. Добавил коммент

2024-10-24 07:31 UTC, pgasheev commented on src/uart-regmap-subsystem.c
> +    irq_handled = -1;
Переделал на bool

2024-10-24 07:31 UTC, pgasheev commented on include/uart-regmap-types.h
> +    uint8_t reserved;
Регистры 16-битные, добавил коммент

2024-10-24 07:33 UTC, pgasheev commented on src/uart-regmap.c
> +void uart_regmap_process_start_tx(const struct uart_descr *u, const struct uart_tx *tx)
Осталось от прошлой архитектуры, убрал

2024-10-24 07:36 UTC, pgasheev commented on src/uart-regmap-subsystem.c
> +        if (regmap_get_data_if_region_changed(uart_descr[i].start_tx_region, &uart_tx_start, sizeof(uart_tx_start))) {
Сбрасывается ниже, перед тем как выдать прерывание set_irq_gpio_active

2024-10-24 07:36 UTC, pgasheev commented on src/uart-regmap-subsystem.c
> +                uart_ctx[i].want_to_tx = 1;
Поправил

2024-10-24 07:37 UTC, pgasheev commented on include/uart-regmap-internal.h
> +    struct {
Хз, отладчиком их смотрел, но в принципе можно и выкинуть

2024-10-24 07:40 UTC, pgasheev commented on src/uart-regmap.c
> +void uart_regmap_process_exchange(const struct uart_descr *u, union uart_exchange *e)
Не согласен, тут кроме TX ещё в rx_data значения сбрасываются

2024-10-24 07:41 UTC, pgasheev commented on src/uart-regmap.c
> +                // При следующем обмене данные будут в формате с ошибками
Следующее после этого очевидно. Раздвинуть не проще - это надо их заново сложить куда-то, потом обратно записать раздвинутыми, а если не влезут? Ну в принципе можно добавить проверку что если меньше половины буфера - то раздвинуть

2024-10-24 07:46 UTC, pgasheev commented on src/uart-regmap.c
> +    ATOMIC {
Завернул

2024-10-24 08:29 UTC, nikitoz236 commented on include/uart-regmap-types.h
> +        struct {
саму структуру хранящую байт данных и ошибку обьявить отдельно. можно сделать ее юнионом с 16 битным словом, копировать за один такт. но главное что это дно и тоже от кольцевого буфера до отправки в SPI

2024-10-24 08:49 UTC, nikitoz236 commented on src/uart-regmap-subsystem.c
> +    irq_handled = -1;
сделать гарантированный минимальный интервал после предыдущего прерывания. чтобы код не зависел от той частоты с которой его вызывают. использовать переменную irq_pending

2024-10-24 09:10 UTC, nikitoz236 commented on src/uart-regmap-subsystem.c
> +        if (regmap_get_data_if_region_changed(uart_descr[i].start_tx_region, &uart_tx_start, sizeof(uart_tx_start))) {
напиши комент что там валидна запись 1 поверх 1, мы никогда не сбрасываем регмап в 0. так как врайт онли регион

2024-10-24 09:23 UTC, nikitoz236 commented on src/uart-regmap-subsystem.c
> +            if (!exchange_received[i]) {
изза того что линия irq одна, exchange_region переписывается по SPI целиком за раз, на оба UARTа. Достаем мы их по половине для одного UART за раз. 

на флаге в if написать что ждем когда обе половины извлекли из regmap

2024-10-24 10:40 UTC, pgasheev commented on src/uart-regmap-subsystem.c
> +        if (regmap_get_data_if_region_changed(uart_descr[i].start_tx_region, &uart_tx_start, sizeof(uart_tx_start))) {
Добавил

2024-10-24 10:42 UTC, pgasheev commented on src/uart-regmap.c
> +                // При следующем обмене данные будут в формате с ошибками
Добавил

2024-10-24 10:59 UTC, pgasheev commented on include/uart-regmap-types.h
> +        struct {
Сделал

2024-10-24 11:02 UTC, pgasheev commented on src/uart-regmap-subsystem.c
> +    irq_handled = -1;
Добавил коммент

2024-10-24 11:15 UTC, pgasheev commented on src/uart-regmap-subsystem.c
> +            if (!exchange_received[i]) {
Переделал

2024-10-24 12:10 UTC, nikitoz236 approved these changes

2024-10-24 12:17 UTC, merged