Feature/wbmz test
wirenboard/wb-embedded-controller pull request #50
Opened 2024-09-26 12:53 UTC by pgasheev

Добавил возможность управлять линиями WBMZ напрямую. Понадобилось для производственных тестов

2024-09-26 14:21 UTC, ad7718 commented on src/wbmz-common.c
> +    static bool charge_force_enabled = false;
непонятное название у переменной, не понимаю чем отличается от предыдущей, если не вычитываться в код

2024-09-26 14:25 UTC, ad7718 requested changes

2024-09-26 14:25 UTC, ad7718 commented on src/wbmz-common.c
> +static bool stepup_force_control = false;
здесь тоже

2024-09-26 17:18 UTC, pgasheev commented on src/wbmz-common.c
> +    static bool charge_force_enabled = false;
Переименовал

2024-09-27 09:30 UTC, ad7718 requested changes

2024-09-27 09:30 UTC, ad7718 commented on src/wbmz-common.c
> +    static bool charge_force_ctll_state = false;
charge_force_ctrl_enabled

2024-09-27 09:30 UTC, ad7718 commented on src/wbmz-common.c
> +    static bool charge_force_ctrl_mode = false;
здесь переменная называется mode, но тип bool - непонятно

2024-09-27 09:56 UTC, pgasheev commented on src/wbmz-common.c
> +    static bool charge_force_ctll_state = false;
Готово

2024-09-27 10:11 UTC, ad7718 commented on src/wbmz-common.c
> +    static bool charge_force_ctll_state = false;
тут опечатка

2024-09-27 10:19 UTC, pgasheev commented on src/wbmz-common.c
> +    static bool charge_force_ctll_state = false;
fixed

2024-09-27 10:20 UTC, ad7718 approved these changes

2024-09-27 11:39 UTC, merged