Feature/wb85 shared gpio
wirenboard/wb-embedded-controller pull request #52
Opened 2024-09-27 11:50 UTC by pgasheev

2024-09-27 21:48 UTC, ad7718 requested changes

2024-09-27 21:48 UTC, ad7718 commented on src/usart_tx.c
>  /**
тут можно опечатку поправить

2024-09-27 21:48 UTC, ad7718 commented on src/gpio-subsytem.c
> +    bool v_in_is_proper_range = vmon_get_ch_status(VMON_CHANNEL_V_OUT);
v_in_is_in_proper_range

2024-09-27 21:48 UTC, ad7718 commented on src/usart_tx.c
> +    check_debug_uart_initialized();
функция называется check, но ничего не возвращает, значит надо чтоб возвращала или назвать "init_debug_uart_if_not_initialized"

2024-09-30 06:57 UTC, pgasheev commented on src/usart_tx.c
>  /**
Не очень понял, какую опечатку?

2024-09-30 06:57 UTC, pgasheev commented on src/gpio-subsytem.c
> +    bool v_in_is_proper_range = vmon_get_ch_status(VMON_CHANNEL_V_OUT);
Поправил

2024-09-30 06:58 UTC, pgasheev commented on src/usart_tx.c
> +    check_debug_uart_initialized();
Переименовал

2024-09-30 09:27 UTC, ad7718 requested changes

2024-09-30 09:27 UTC, ad7718 commented on src/usart_tx.c
>  /**
Не в этом ПР, номожно поправить заодно - строка 11, слово "явновно" - опечатка

2024-09-30 09:32 UTC, pgasheev commented on src/usart_tx.c
>  /**
Исправил

2024-09-30 11:20 UTC, merged