gpio-subsytem: Initialize gpio_dir as constant
wirenboard/wb-embedded-controller pull request #60
Opened 2024-11-16 13:06 UTC by Ilia1S

2024-11-18 07:04 UTC, pgasheev requested changes
Описания нет, проверки не проходят

2024-11-18 07:04 UTC, pgasheev commented on src/gpio-subsytem.c
> +    .gpio_dir = BIT(EC_EXT_GPIO_V_OUT),
Константу outputs_only_gpios вместе с inputs_only_gpios нужно тогда вообще удалить. Оформить их дефайнами

2024-11-19 11:11 UTC, pgasheev requested changes
Нет описания PR

2024-11-20 08:00 UTC, Ilia1S commented on src/gpio-subsytem.c
> +#define OUTPUTS_ONLY_GPIOS (BIT(EC_EXT_GPIO_V_OUT))
ОК

2024-12-16 11:46 UTC, pgasheev requested changes

2024-12-16 11:46 UTC, pgasheev commented on src/gpio-subsytem.c
> +    gpio_ctx.gpio_ctrl &= ~INPUTS_ONLY_GPIOS;
Здесь нужно перечислить именно А1-А4, а не INPUTS_ONLY_GPIOS

2024-12-16 11:46 UTC, pgasheev commented on src/gpio-subsytem.c
> +    gpio_ctx.gpio_ctrl &= OUTPUTS_ONLY_GPIOS;
Оставить как было, даже коммент есть почему так

2024-12-16 11:46 UTC, pgasheev commented on debian/changelog
> + wb-ec-firmware (2.0.1) stable; urgency=medium
Тут пробел лишний в начале строки как будто

2026-05-28 08:52 UTC, closed without merging